pipeline:
  name: python-test-pipeline
  identifier: pythontestpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1715259429427
        repoName: unoffash/repo1
        build: <+input>
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1 - install SnowSQL
                  identifier: Run_1_install_python_dependencies
                  spec:
                    shell: Sh
                    command: |-
                      wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowflake-snowsql-1.2.21-1.x86_64.rpm
                      rpm -i snowflake-snowsql-1.2.21-1.x86_64.rpm
                      snowsql -v
              - step:
                  type: Run
                  name: Run_2 - execute SQL script for stored procedure
                  identifier: Run_2
                  spec:
                    shell: Bash
                    command: |-
                      #!/bin/bash

                      snowsql -a $ACCOUNT -u "$USERNAME" -d "$DATABASE" -s "$SCHEMA" -f "$SQL_FILE"
