pipeline:
  name: python-test-pipeline
  identifier: pythontestpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1715259429427
        repoName: unoffash/repo1
        build: <+input>
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1 - install SnowSQL
                  identifier: Run_1_install_python_dependencies
                  spec:
                    shell: Sh
                    command: |-
                      wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowflake-snowsql-1.2.21-1.x86_64.rpm
                      rpm -i snowflake-snowsql-1.2.21-1.x86_64.rpm
                      snowsql -v
              - step:
                  type: Run
                  name: Run_2 - execute SQL script for stored procedure
                  identifier: Run_2
                  spec:
                    shell: Bash
                    command: |-
                      #!/bin/bash

                      snowsql -a $ACCOUNT -u "$USERNAME" -d "$DATABASE" -s "$SCHEMA" -f "$SQL_FILE"
                    envVariables:
                      ACCOUNT: rxrkbxe-dw20573
                      USERNAME: ASHP123
                      SNOWSQL_PWD: Idkth3sfpass@123
                      DATABASE: HARNESSDB
                      SCHEMA: HARNESSSCHEMA
                      SQL_FILE: storedproc.sql
              - step:
                  type: Run
                  name: Run_3 - Execute SQL to create task
                  identifier: Run_3_Execute_SQL_to_create_task
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash

                      snowsql -a $ACCOUNT -u "$USERNAME" -d "$DATABASE" -s "$SCHEMA" -f "$SQL_FILE"
                    envVariables:
                      ACCOUNT: rxrkbxe-dw20573
                      USERNAME: ASHP123
                      SNOWSQL_PWD: Idkth3sfpass@123
                      DATABASE: HARNESSDB
                      SCHEMA: HARNESSSCHEMA
                      SQL_FILE: testtask.sql
              - step:
                  type: Run
                  name: Run_4 - Execute task
                  identifier: Run_4_Execute_task
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash

                      snowsql -a $ACCOUNT -u "$USERNAME" -d "$DATABASE" -s "$SCHEMA" -f "$SQL_FILE"
                    envVariables:
                      ACCOUNT: rxrkbxe-dw20573
                      USERNAME: ASHP123
                      SNOWSQL_PWD: Idkth3sfpass@123
                      DATABASE: HARNESSDB
                      SCHEMA: HARNESSSCHEMA
                      SQL_FILE: execute_task.sql
    - stage:
        name: Approval Stage
        identifier: Approval_Stage
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approval Step
                  identifier: Approval_Step
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: stage2-prod
        identifier: stage2prod
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1 _ check snowsql version
                  identifier: Run_1___check_snowsql_version
                  spec:
                    shell: Sh
                    command: snowsql -v
