name: tfg feature 3 code

on:
  push:
    branches: [ feature3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage

    - name: Run tests with coverage
      run: |
          coverage run -m pytest 
    - name: Generate coverage report
      run: |
          coverage report
          coverage html
    - name: Check coverage threshold
      run: |
          coverage report --fail-under=90
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov
